name:                qura
version:             0.1.0.0
github:              "andreacolledan/qura"
license:             MIT
author:              "Andrea Colledan"
maintainer:          "andreacolledan@fastmail.com"
copyright:           "Copyright (c) 2024–2025 Andrea Colledan"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/andreacolledan/qura#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- mtl
- unordered-containers
- extra
- hspec
- process
- filepath
- megaparsec
- parser-combinators
- argparser
- optparse-applicative
- ansi-terminal
- QuickCheck
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-top-binds
- -Wincomplete-patterns
- -Wno-name-shadowing

library:
  source-dirs: src

executables:
  qura:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qura

tests:
  qura-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qura
